### ISSUE TITLE
spring boot 프로젝트 생성

### ISSUE THREAD

**Issue by jeon-seun** [jeon-seun/spring-todolist#1]
**기능 설명**
todo list 웹 애플리케이션 제작을 위한 spring boot 프로젝트 생성 및 초기작업

**구현 방향**
기본적인 spring boot 프로젝트로 생성 할 것
gradle 기반으로 생성 할 것

**Todo**
- [ ] spring boot 프로젝트 생성
- [ ] spring webmvc 의존성 추가
- [ ] spring thymeleaf 의존성 추가
- [ ] spring data jpa 의존성 추가
